---
version: 2
jobs:
  # Build recent stable Linux kernel, with no patches
  vanilla:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - run: apt-get install -y make build-essential
      - run: ./go.sh
workflows:
  version: 2
  build:
    jobs:
      - vanilla
