---
version: 2
jobs:
  # Build recent stable Linux kernel, with no patches
  vanilla:
    docker:
      - image: circleci/python:buster
    steps:
      - checkout
      - setup_remote_docker
      - mkdir -p /tmp/kernels && chmod 777 /tmp/kernels
      - run: sudo apt-get update && sudo apt-get install -y make build-essential
      - run: ./go.sh
workflows:
  version: 2
  build:
    jobs:
      - vanilla
