---
version: 2
jobs:
  # Build recent stable Linux kernel, with no patches
  vanilla:
    machine:
      image: ubuntu-2004:202010-01
    # Can't use volume mounts in CircleCI with docker driver
    # docker:
    #   - image: circleci/python:buster
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y make build-essential
      - run: make vanilla
  # Run reprotest to confirm reproducible builds
  reproducibility:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y make build-essential reprotest
      - run: make reprotest
workflows:
  version: 2
  build:
    jobs:
      - vanilla
      - reproducibility
